export function etcNutrientFunc({
  sugars,
  fiber,
  calcium,
  iron,
  phosphorus,
  potassium,
  salt,
  cholesterol,
  saturatedfat,
  transfat,
}) {
  return [
    {
      name: "당분",
      type: "sugars",
      value: sugars,
      color: "#FFBB4C",
      width: sugars,
      unit: "g",
    },
    {
      name: "식이섬유",
      type: "fiber",
      value: fiber,
      color: "#F47676",
      width: (fiber / 25) * 300,
      unit: "g",
    },
    {
      name: "칼슘",
      type: "calcium",
      value: calcium,
      color: "#D1D5E0",
      width: (calcium / 800) * 300,
      unit: "mg",
    },
    {
      name: "철분",
      type: "iron",
      value: iron,
      color: "#9B82A5",
      width: (iron / 100) * 300,
      unit: "㎍",
    },
    {
      name: "인",
      type: "phosphorus",
      value: phosphorus,
      color: "#87827B",
      width: (phosphorus / 700) * 300,
      unit: "mg",
    },
    {
      name: "칼륨",
      type: "potassium",
      value: potassium,
      color: "#FFDCE1",
      width: (potassium / 3500) * 300,
      unit: "mg",
    },
    {
      name: "나트륨",
      type: "salt",
      value: salt,
      color: "#47B8E0",
      width: (salt / 1500) * 300,
      unit: "mg",
    },
    {
      name: "트랜스지방산",
      type: "transfat",
      value: transfat,
      color: "#9494E0",
      width: transfat * 300,
      unit: "g",
    },
    {
      name: "포화지방산",
      type: "saturatedfat",
      value: saturatedfat,
      color: "#6565D8",
      width: saturatedfat,
      unit: "g",
    },
    {
      name: "콜레스테롤",
      type: "cholesterol",
      value: cholesterol,
      color: "#008729",
      width: cholesterol,
      unit: "mg",
    },
  ];
}

export function vitaminNutrientFunc({vitaminA, vitaminC, vitaminD}) {
  return [
    {
      name: "A",
      type: "vitaminA",
      value: vitaminA,
      color: "#FFE54D",
      width: (vitaminA / 800) * 100,
      unit: "㎍",
    },
    {
      name: "C",
      type: "vitaminC",
      value: vitaminC,
      color: "#FFFB66",
      width: vitaminC * 300,
      unit: "㎍",
    },
    {
      name: "D",
      type: "vitaminD",
      value: vitaminD,
      color: "#E9FF66",
      width: (vitaminD / 10) * 300,
      unit: "㎍",
    },
  ];
}
